export const OverviewDashboardConstants = {
    GET_DASHBOARD_MARKET_CAP_VOLUME_REQUEST: 'GET_DASHBOARD_MARKET_CAP_VOLUME_REQUEST',
    GET_DASHBOARD_MARKET_CAP_VOLUME_SUCCESS: 'GET_DASHBOARD_MARKET_CAP_VOLUME_SUCCESS',
    GET_DASHBOARD_MARKET_CAP_VOLUME_FAILURE: 'GET_DASHBOARD_MARKET_CAP_VOLUME_FAILURE',

    GET_DASHBOARD_MARKET_PLACE_TREND_REQUEST: 'GET_DASHBOARD_MARKET_PLACE_TREND_REQUEST',
    GET_DASHBOARD_MARKET_PLACE_TREND_SUCCESS: 'GET_DASHBOARD_MARKET_PLACE_TREND_SUCCESS',
    GET_DASHBOARD_MARKET_PLACE_TREND_FAILURE: 'GET_DASHBOARD_MARKET_PLACE_TREND_FAILURE',

    GET_DASHBOARD_HOLDER_REQUEST: 'GET_DASHBOARD_HOLDER_REQUEST',
    GET_DASHBOARD_HOLDER_SUCCESS: 'GET_DASHBOARD_HOLDER_SUCCESS',
    GET_DASHBOARD_HOLDER_FAILURE: 'GET_DASHBOARD_HOLDER_FAILURE',
    
}