export const OverviewDashboardConstants = {
    GET_DASHBOARD_MARKET_CAP_VOLUME_REQUEST: 'GET_DASHBOARD_MARKET_CAP_VOLUME_REQUEST',
    GET_DASHBOARD_MARKET_CAP_VOLUME_SUCCESS: 'GET_DASHBOARD_MARKET_CAP_VOLUME_SUCCESS',
    GET_DASHBOARD_MARKET_CAP_VOLUME_FAILURE: 'GET_DASHBOARD_MARKET_CAP_VOLUME_FAILURE',
}