export const AuctionDashboardConstants = {
  GET_NFT_STATS_REQUEST: 'GET_NFT_STATS_REQUEST',
  GET_NFT_STATS_SUCCESS: 'GET_NFT_STATS_SUCCESS',
  GET_NFT_STATS_FAILURE: 'GET_NFT_STATS_FAILURE',

  GET_AUCTION_VOLUME_REQUEST: 'GET_AUCTION_VOLUME_REQUEST',
  GET_AUCTION_VOLUME_SUCCESS: 'GET_AUCTION_VOLUME_SUCCESS',
  GET_AUCTION_VOLUME_FAILURE: 'GET_AUCTION_VOLUME_FAILURE',

  GET_AUCTION_PARTICIPATE_REQUEST: 'GET_AUCTION_PARTICIPATE_REQUEST',
  GET_AUCTION_PARTICIPATE_SUCCESS: 'GET_AUCTION_PARTICIPATE_SUCCESS',
  GET_AUCTION_PARTICIPATE_FAILURE: 'GET_AUCTION_PARTICIPATE_FAILURE'
};
